[package]
name = "cfgcomment-core"
description = "Core logic of cfgcomment"
license = "MIT"
version = "0.1.0"
edition = "2018"

[dependencies]
ignore = "0.4.18"
log = "0.4.14"
peg = "0.7.0"
tempfile = "3.2.0"
